def device_name_to_path(device_name: str) -> str:
    """Convert device name to filesystem-safe path (replace hyphens with underscores)."""
    return device_name.replace('-', '_')


from .device_info import (
    parse_device_banner,
    get_root_fs_for_core,
    SUPPORT_CORE_DEVICE_TYPES,
    CORE_ROOT_FS,
    DEFAULT_ROOT_FS,
)
from .constants import (
    CTRL_A, CTRL_B, CTRL_C, CTRL_D, CTRL_E,
    REPL_PROMPT, EOF_MARKER,
    RAW_REPL_PROMPT, SOFT_REBOOT_MSG, OK_RESPONSE, ERROR_HEADER,
    RAW_PASTE_INIT, RAW_PASTE_SUPPORTED, RAW_PASTE_NOT_SUPPORTED,
    RAW_PASTE_FALLBACK, RAW_PASTE_WINDOW_INC, RAW_PASTE_END_DATA,
    PORT_SCAN_TIMEOUT, REPL_READ_TIMEOUT,
    SERIAL_TIMEOUT, SERIAL_WRITE_TIMEOUT,
    REPL_BUFSIZE, RAW_PASTE_DEFAULT_WINDOW_SIZE,
    DEVICE_CHUNK_SIZE_DEFAULT, DEVICE_CHUNK_SIZE_EFR32MG,
    PUT_BATCH_BYTES_DEFAULT, PUT_BATCH_BYTES_EFR32MG,
    RAW_MODE_DELAY_DEFAULT, RAW_MODE_DELAY_EFR32MG,
    DEFAULT_AGENT_PORT, MAX_AGENT_PORT, AGENT_HOST,
    MAX_CONNECTIONS, AGENT_SOCKET_TIMEOUT,
    MAX_UDP_SIZE, MAX_PAYLOAD_SIZE,
    HEARTBEAT_INTERVAL, ZOMBIE_CHECK_INTERVAL, IDLE_COMMAND_THRESHOLD,
    GC_THRESHOLD,
)
from .exceptions import (
    ReplxException,
    TransportError,
    SerialError,
    ProtocolError,
    RawReplError,
    RawPasteError,
    ExecutionError,
    FileSystemError,
    DownloadError,
    UploadError,
    CLIError,
    ValidationError,
    CompilationError,
)

__all__ = [
    "device_name_to_path",
    "parse_device_banner",
    "get_root_fs_for_core",
    "SUPPORT_CORE_DEVICE_TYPES",
    "CORE_ROOT_FS",
    "DEFAULT_ROOT_FS",
    "CTRL_A", "CTRL_B", "CTRL_C", "CTRL_D", "CTRL_E",
    "REPL_PROMPT", "EOF_MARKER",
    "RAW_REPL_PROMPT", "SOFT_REBOOT_MSG", "OK_RESPONSE", "ERROR_HEADER",
    "RAW_PASTE_INIT", "RAW_PASTE_SUPPORTED", "RAW_PASTE_NOT_SUPPORTED",
    "RAW_PASTE_FALLBACK", "RAW_PASTE_WINDOW_INC", "RAW_PASTE_END_DATA",
    "PORT_SCAN_TIMEOUT", "REPL_READ_TIMEOUT",
    "SERIAL_TIMEOUT", "SERIAL_WRITE_TIMEOUT",
    "REPL_BUFSIZE", "RAW_PASTE_DEFAULT_WINDOW_SIZE",
    "DEVICE_CHUNK_SIZE_DEFAULT", "DEVICE_CHUNK_SIZE_EFR32MG",
    "PUT_BATCH_BYTES_DEFAULT", "PUT_BATCH_BYTES_EFR32MG",
    "RAW_MODE_DELAY_DEFAULT", "RAW_MODE_DELAY_EFR32MG",
    "DEFAULT_AGENT_PORT", "MAX_AGENT_PORT", "AGENT_HOST",
    "MAX_CONNECTIONS", "AGENT_SOCKET_TIMEOUT",
    "MAX_UDP_SIZE", "MAX_PAYLOAD_SIZE",
    "HEARTBEAT_INTERVAL", "ZOMBIE_CHECK_INTERVAL", "IDLE_COMMAND_THRESHOLD",
    "GC_THRESHOLD",
    "ReplxException",
    "TransportError",
    "SerialError",
    "ProtocolError",
    "RawReplError",
    "RawPasteError",
    "ExecutionError",
    "FileSystemError",
    "DownloadError",
    "UploadError",
    "CLIError",
    "ValidationError",
    "CompilationError",
]